export const TRY_LOGIN = 'TRY_LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_REQUEST_COMPLETE = 'LOGIN_REQUEST_COMPLETE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
