export default [
	{
		correctAnswer: '1983',
		answers: ['1822', '1934', '1983', '1984'],
		question: 'What year did Skoal, a smokeless Tobacco company, release their first line of Pouches, known as Skoal Bandits?',
		id: 'Up1VwwChxMIyjVwx5IUZ',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Monopoly',
		answers: ['Clue', 'Risk', 'Monopoly', 'Candy Land'],
		question: 'Which board game was first released on February 6th, 1935?',
		id: 'pYjDGv7YFDQtF9n1kp7R',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Church',
		answers: ['Church', 'Synagogue', 'Temple', 'Mosque'],
		question: 'Irish musician Hozier released a music track in 2013 titled, Take Me to ______',
		id: 'OrCj7OGLz6EihnilXQEj',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Lake Superior',
		answers: ['Lake Michigan', 'Lake Superior', 'Lake Huron', 'Caspian Sea'],
		question: 'Which is the largest freshwater lake in the world?',
		id: '03RZujpn4yzea8UOAifV',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Marie Antoinette',
		answers: ['Elizabeth I', 'Czar Nicholas II', 'Marie Antoinette', 'Henry VIII'],
		question: 'Which famous world leader is famed for the saying, Let them eat cake, yet is rumored that he/she never said it at all?',
		id: 'aRm6goujhkIy14fyyoQI',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'center',
		answers: ['relative', 'static', 'absolute', 'center'],
		question: 'In CSS, which of these values CANNOT be used with the position property?',
		id: '6uecVOAz94L0eNG9Obff',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Stack',
		answers: ['Heap', 'Tree', 'Queue', 'Stack'],
		question: 'Which data structure does FILO apply to?',
		id: 'dPXa0OaFXKvsTjaI87HU',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'The Falador Massacre',
		answers: ['TzHaar Massacre', 'The Falador Massacre', 'Noclip glitch', 'Party-hat Duplication Glitch'],
		question: 'On the 6th of June 2006, what was the name of the infamous glitch that occurred in the MMO RuneScape?',
		id: 'hfsuKvnrsA0zdPwwEBcM',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Thunder',
		answers: ['Ice', 'Thunder', 'Fire', 'Water'],
		question: 'What element does the Zinogre use in Monster Hunter?',
		id: 'ouGjLzE8T5e8UFeqVyf4',
		selectedAnswer: null,
		isCorrect: null,
	},
	{
		correctAnswer: 'Elric',
		answers: ['Elwood', 'Ellis', 'Elric', 'Eliek'],
		question: 'What is the last name of Edward and Alphonse in the Fullmetal Alchemist series.',
		id: 'AoXV7G4x21raruH2Q4BZ',
		selectedAnswer: null,
		isCorrect: null,
	},
];
